import "@app/_styles/globals.scss";
import type { Metadata } from "next";
import { Vazirmatn } from "next/font/google";
import { ReactNode } from "react";
import { MantineProvider } from "@mantine/core";
import { ToastContainer } from "react-toastify";

const vazirmatn = Vazirmatn({
  weight: ["300", "400", "500", "600", "700", "800", "900"],
  subsets: ["arabic", "latin"],
  variable: "--font-vazirmatn",
  display: "swap"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }: { children: ReactNode }): ReactNode {
  return (
    <MantineProvider theme={{ fontFamily: "Open Sans" }} withGlobalStyles withNormalizeCSS>
      <ToastContainer rtl={false} pauseOnFocusLoss className={vazirmatn.className} />
      <html lang="en" className={`${vazirmatn.variable}`}>
        <body className={vazirmatn.className}>{children}</body>
      </html>
    </MantineProvider>
  );
}
