export const global = {
  title: "سیستم ارسال نوتیفیکیشن الکترونیک",
  description: "Generated by create next app",
  copyright: "تمامی حقوق مادی و معنوی این پنل متعلق به ویستا سامانه آسا می‌باشد."
};
